version : "3.4"
services:
    ghost:
        image: ghost:1-alpine
        restart: always
        ports:
            - 2368:2368
        volumes:
            - type: bind
              source: ./content
              target: /var/lib/ghost/content